services:
  # Main python web service
  - type: web
    name: how2meet
    runtime: python
    repo: https://github.com/BenMemberg/how2meet.git
    region: ohio
    plan: free
    branch: main
    buildCommand: poetry install
    startCommand: poetry run make run_server
    envVars:
      - key: DB_CONN
        fromDatabase:
          name: how2meet-db
          property: connectionString
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
    buildFilter:
      paths: # Only rebuild on changes to these paths
        - how2meet/**/*
      ignoredPaths: # Don't rebuild on changes to these paths
        - tests/**/*
        - docs/**/*

databases:
  - # Postgres database instance on render
  - name: how2meet-db
    plan: free
    region: ohio

