services:
  # Main python web service
  - type: web
    name: how2meet
    runtime: python
    repo: https://github.com/BenMemberg/how2meet.git
    branch: deploy
    region: ohio
    plan: free
    buildCommand: make install
    startCommand: poetry run make run_server
    autoDeploy: true
    envVars:
      - key: BASE_URL
        value: https://www.how2meet.com
      - key: DB_CONN
        fromDatabase:
          name: how2meet-db
          property: connectionString
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
      - key: H2M_EMAIL_APP_PASSWORD
        sync: false
    buildFilter:
      paths: # Only rebuild on changes to these paths
        - how2meet/**/*
      ignoredPaths: # Don't rebuild on changes to these paths
        - tests/**/*
        - docs/**/*

databases:
  - # Postgres database instance on render
  - name: how2meet-db
    plan: free
    region: ohio
