"""rename event password

Revision ID: 1216a96fe98b
Revises: 4b5f97fcf539
Create Date: 2024-02-27 10:38:56.058806

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1216a96fe98b"
down_revision: Union[str, None] = "4b5f97fcf539"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('events', sa.Column('event_password', sa.String(length=100), nullable=True))
    # op.drop_column('events', 'auth_token')
    op.alter_column("events", "auth_token", new_column_name="event_password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('events', sa.Column('auth_token', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # op.drop_column('events', 'event_password')
    op.alter_column("events", "event_password", new_column_name="auth_token")

    # ### end Alembic commands ###
