ROUTE_PREFIX_EVENTS = "/events"
ROUTE_EVENTS_LIST = "/"
ROUTE_NEW_EVENT = "/new_event"
ROUTE_EVENT_HOME = "/home/{event_id}"

URL_EVENTS = ROUTE_PREFIX_EVENTS + ROUTE_EVENTS_LIST
URL_NEW_EVENT = ROUTE_PREFIX_EVENTS + ROUTE_NEW_EVENT
URL_EVENT_HOME = ROUTE_PREFIX_EVENTS + ROUTE_EVENT_HOME
