name: Pre-commit Workflow
on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - uses: pre-commit/action@v3.0.1
      continue-on-error: true
#    - uses: pre-commit-ci/lite-action@v1.0.2
#      if: always()
#      continue-on-error: true
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "linting via pre-commit setup"
